site:
  title: Dokumentation xmera Omnia
  url: /
  start_page: xmera-omnia-dokumentation:ROOT:index.adoc
content:
  sources: 
  - url: .
    # tags: [0.1, 0.3]
    branches: HEAD
    start-paths: .
  - url: ../xo_guide
    branches: HEAD
    start_path: .
  - url: ../xo_demo_guide
    branches: HEAD
    start_path: .

ui:
  bundle:
    url: https://github.com/xmera-circle/antora-ui-omnia/releases/download/0.3.0/ui-bundle.zip
    snapshot: true

antora:
  extensions:
  - require: '@antora/lunr-extension'

